name: campus_connect
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  uuid: ^4.0.0
  url_launcher: ^6.2.5
  image_picker: ^0.8.7+4

  cupertino_icons: ^1.0.8
  http: ^0.13.5
  record: ^5.0.0
  just_audio: ^0.9.36
  path_provider: ^2.1.2

  firebase_core: ^2.32.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.17.5
  cloud_functions: ^4.6.5
  font_awesome_flutter: ^10.6.0
  file_picker: ^6.1.1
  firebase_storage: ^11.5.2
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.17
  



dev_dependencies:
  flutter_lints:    ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/ai_icon.jpg
    - assets/images/courses.jpg
    - assets/images/discussions.jpg
    - assets/images/guidance.jpg
    - assets/images/queries.jpg
    - assets/images/profiles.jpg
    - assets/images/student1.jpg
    - assets/images/student2.jpg
    - assets/images/student3.jpg
    - assets/images/student4.jpg
    - assets/images/student5.jpg
    - assets/images/google_logo.webp
    - assets/images/profile.jpg
    - assets/images/user.jpg
    - assets/images/4ty_logo.jpg
    - assets/images/student6.jpg
    - assets/images/student7.jpg
    - assets/images/student8.jpg
    - assets/images/student9.jpg
    - assets/images/student10.jpg
    - assets/images/student11.jpg
    - assets/images/student12.jpg
    - assets/images/student13.jpg
    - assets/images/student14.jpg
    - assets/images/student15.jpg
    - assets/images/student16.jpg
    - assets/images/default_avatar.jpg

